### ISSUE TITLE
React Native UI framework

### ISSUE THREAD

**Issue by rturk** [metafizzy/next-project#11]
Mobile Apps are the new frontier. React Native is the new tool to build apps, however it lacks a decent UI framework.

**Comment by desandro** [comment]
Thanks for submitting this proposal. **+1 this issue** if you'd like to see a React UI framework from Metafizzy.

I'm curious: isn't React a UI framework in of itself? What features would you like in this add-on framework (grid, transitions, modals, etc )? cc @ianstormtaylor

**Comment by jokeyrhyme** [comment]
React Native is a cross-platform approach, but views are still coded using platform-specific widgets. Developers need to know the iOS name for a button, and the Android name for a button, for example.

I'm going to assume this is proposal is for a unified abstraction layer on top of React Native. So, for example, there's just the one button widget and it automatically expresses itself as appropriate for each platform.

**Comment by ianstormtaylor** [comment]
Yeah, need a better term. But I think people mean UI as in toggles, buttons, icons, etc. that are pre-packaged and easy to use, so they don't have to write things like "hide dropdown on clicking outside of it" logic over and over, but still easily themeable. In this case too, @rturk is talking about one for native as in for iOS/Android use I think. 

Also another repository working towards something like it: https://github.com/nikgraf/future-react-ui

**Comment by bradmurray** [comment]
https://www.decosoftware.com/

**Comment by desandro** [comment]
Thanks for this suggestion. React is not in my wheelhouse so I'll pass on this one 🐳
