### ISSUE TITLE
React UI framework

### ISSUE THREAD

**Issue by ianstormtaylor** [metafizzy/next-project#12]
Don't know if you're interested in going React-specific, but since I was recently tweeting about it :) I feel like there's a way to make a good one, that's not a pain to theme, and that's not overly opinionated leading to poor reuse.

If I think of other stuff I'll add issues, cool idea!

**Comment by desandro** [comment]
Thanks pal! Sounds similar to #11. React is not currently my thing, but sounds like people are interested in this.
