### ISSUE TITLE
When does this end? The suspense is killing me

### ISSUE THREAD

**Issue by corysimmons** [metafizzy/next-project#16]
Also, when you decide, will you ping us somehow? Maybe we could subscribe to a locked announcement thread instead of getting hit with +1's all day. :)

**Comment by desandro** [comment]
First off, thanks so much for your support! Your interest in Metafizzy is encouraging :blush: 

Metafizzy's next project is not going to start until the 2nd half of 2016. I'm currently working on major releases of all of Metafizzy's product: Packery (v2 comes out next week!), Isotope, and Flickity. Until then, I'm interested to see what people want.

Looking at the current votes, it's likely going to be Infinite Scroll v2 or Droppabilly. Both are big undertakings. I'd estimate 4 months of development time to get either of these projects released. If it all works out, Metafizzy will have 4 products by the end of the 2016.

As for the +1 pings, I recommend unsubscribing from these threads. Yes, I'll make a big announcement. Follow [@metafizzyco](https://twitter.com/metafizzyco) for updates on all the projects, as well as the next thing. I'll also be creating an email newsletter for bigger announcements. I'll follow up once that's available.

**Comment by corysimmons** [comment]
[I don't have Twitter anymore](https://www.youtube.com/watch?v=jSJQEl5vcAo) but I'm sure I'll bump into it sooner or later. Reeeeeally hope it's the infinite scroll. :heart: your work.

**Comment by desandro** [comment]
Sign up for email newsletter http://eepurl.com/bSZzjj

**Comment by corysimmons** [comment]
Nah, newsletters are completely ruined for me. Too many promises of "We promise not to spam you!" followed by 2-3 emails a week.

It's cool, I'm sure I'll stumble upon it shortly after it launches. :+1:
