### ISSUE TITLE
KanBan board

### ISSUE THREAD

**Issue by joewalling** [metafizzy/next-project#18]
A Kanban board where you can drag and drop items from 1 container to the next. For example, the containers could be New, In Progress, In Testing, and Done. As a task progresses, it is dragged from one container to the next. It would be nice if these containers could be dynamically generated as the workflow may be different for different organizations. Webix has a Kanban control much like what I would like. I'm willing to fund some of the development.

**Comment by desandro** [comment]
Thanks for this proposal! I'm curious, would a generalized drag & drop library a suitable solution? See #1

**Comment by joewalling** [comment]
Hi David:

It would get a good portion of the way there. The reason I posted my request was that I was looking at Metafizzy and how you could drag items around in a single container and was thinking that if you could apply that concept to dragging and dropping to a different container probably wouldn’t be that much work over metafizzy. I could go out and license Webix (http://webix.com/kanban/) as they have a Kanban board, but my research suggests, there isn’t much out there doing this same thing. However, I don’t want to buy into their approach and other libraries that go with it.

If you look at a lot of the modern CRM systems, they are implementing Kanban type systems.

I have a CRM/Project Management application and am currently using grids. However, they don’t allow all the functionality I want and they aren’t readily made responsive in a way that still shows the info well. A Kanban board would.

Best Regards,
Joe Walling
864-905-8809
[WallingInfoSystemLogoWithColor Signature]http://wallingis.com/
Building Software to Improve Your Profit

**Comment by desandro** [comment]
Thank you for this suggestion. I have decided not to pursue this idea. I appreciate your input and hope you continue to be involved in open source. Metafizzy thanks you! 🌈🐻
