### ISSUE TITLE
Infinite Scroll v2

### ISSUE THREAD

**Issue by desandro** [metafizzy/next-project#2]
[Infinite Scroll](https://github.com/infinite-scroll/infinite-scroll/#readme) is no longer maintained :cry:. Infinite Scroll was the OG of awesome front-end widgets. It needs a proper re-vitalization.

> the only way forward with this project is a 100% rewrite with a new API.
### Features
- Events - `scrollBottomHit`, `requestingNextPage`, `nextPageResponse`, `nextPageAdded`
- A flexible API for handling what to do when getting the next page
  - get next page HTML, add it to page
  - get next page's data, compile it in template, add it to page
  - extra stuff: tooltips, lazyLoad, video js, etc.
- Masonry, Isotope, Packery integration
- no jQuery dependency
- Doesn't break the back button
- Update URL. Scrolling to `/page2`'s content update's the URL to `/page2`
- Promises?

---

**Add your 👍  reaction** if you'd like to see Metafizzy release Infinite Scroll v2.

**Comment by dennisgaebel** [comment]
+1

**Comment by ademilter** [comment]
+1

**Comment by nkpgardose** [comment]
+1

**Comment by sawyerh** [comment]
+1 (Please add "Don't break the back button" to the features? :smiley:)

**Comment by kingkool68** [comment]
+1

This is how I handled infinite scroll for an archive page on PewResearch.org https://gist.github.com/kingkool68/9277919

Here's a fun edge case:
Say you're infinitely scrolling through a page and some pages have JS to handle video. You have to check the script dependencies of each page and if you find a new script src inject that into the page. 

Like http://zadieheimlich.com. Some pages have video on them that depend on http://cdn.zadieheimlich.com/wp-includes/js/mediaelement/mediaelement-and-player.min.js?ver=2.18.1 and http://cdn.zadieheimlich.com/wp-includes/js/mediaelement/wp-mediaelement.js?ver=4.4.1

**Comment by howells** [comment]
+1

**Comment by desandro** [comment]
@sawyerh Good call on back button stuff. Added to feature list

**Comment by richgcook** [comment]
+1

**Comment by seb-thomas** [comment]
This would be great. Adding some kind of pagination would super cool too, as per this blog post:
https://googlewebmastercentral.blogspot.co.uk/2014/02/infinite-scroll-search-friendly.html

Demo:
http://scrollsample.appspot.com/items

**Comment by idleberg** [comment]
+1

**Comment by amdad** [comment]
+1

**Comment by mrdoinel** [comment]
+1

**Comment by macsupport** [comment]
+1

**Comment by stephenjwatkins** [comment]
+1

**Comment by abrad45** [comment]
+1

**Comment by aderaaij** [comment]
+1
Sounds like a mighty challenge, but songs will be written about you if you pull it off.

**Comment by dariodev** [comment]
+1
events, back button, update url  :thumbsup:

**Comment by zachwinnie** [comment]
+1

**Comment by JourneyRossOld** [comment]
+1

**Comment by urcades** [comment]
+1

**Comment by corysimmons** [comment]
:+1: [the pagination option](https://github.com/metafizzy/next-project/issues/2#issuecomment-175085006) is a wonderful idea.

**Comment by sambaldwin** [comment]
:+1:

**Comment by patrick-wc** [comment]
+1 with an option to load in X times then have a "load more" button

**Comment by DanielWeitenauer** [comment]
+1

**Comment by bicrazor** [comment]
+1

**Comment by tienvooracht** [comment]
+1

**Comment by KnightAlex** [comment]
+1

**Comment by bradmurray** [comment]
+1

**Comment by viocassel** [comment]
+1

**Comment by esiao** [comment]
+1 and Isotope integration would be the best, I managed to create an infinite scroll script working with filters and load more button on a WordPress instance. But having a library for this working on every project would be a great value.

**Comment by dreammonkey** [comment]
+1

**Comment by nageshtiwari-dp** [comment]
+1

**Comment by discoliam** [comment]
+1

**Comment by Bouwyn** [comment]
+1

**Comment by omidantilong** [comment]
+1

**Comment by sajpasa** [comment]
+1

**Comment by SelimSalihovic** [comment]
+1

**Comment by amdad** [comment]
+1

**Comment by JonathanJonathanJonathan** [comment]
+1

**Comment by Luxbit** [comment]
+1

**Comment by otravers** [comment]
+1

**Comment by derWebdesigner** [comment]
+1

**Comment by karlobencic** [comment]
+1

**Comment by federico77** [comment]
+1

**Comment by itwseood** [comment]
+1

**Comment by MALIK-0** [comment]
+1

**Comment by fuseblue** [comment]
+1

**Comment by marat93** [comment]
+1

**Comment by arnoldmontiel** [comment]
+1

**Comment by DamirPecnik** [comment]
+1

**Comment by golgote** [comment]
+1

**Comment by hgassen** [comment]
+1

**Comment by wingski** [comment]
+1

**Comment by hblackett** [comment]
+1

**Comment by empz** [comment]
+1

**Comment by leeralls** [comment]
+1

**Comment by centrual** [comment]
+1 It's really needed. (with virtual areas - display only visible area items ability is better )

**Comment by pgraci** [comment]
+1

**Comment by dragonfire1119** [comment]
+1

**Comment by habieb** [comment]
+1

**Comment by destruc7i0n** [comment]
+1

**Comment by martabotter** [comment]
+1

**Comment by PaoloFalomo** [comment]
+1

**Comment by fgilio** [comment]
+1

**Comment by tkyeung357** [comment]
+1

**Comment by NicolasGraph** [comment]
+1

**Comment by eldair** [comment]
+1

**Comment by spigotdesign** [comment]
+1

**Comment by JosephusPaye** [comment]
+1

**Comment by kimsondrup** [comment]
+1

**Comment by dmitryvmin** [comment]
+1

**Comment by AlanRice93** [comment]
+1

**Comment by danrichman** [comment]
👍

**Comment by pkostadinov-2create** [comment]
+1

**Comment by Judahmeek** [comment]
+1 Would https://github.com/pklauzinski/jscroll make a good starting point?

**Comment by vDeggial** [comment]
+1(+100)

**Comment by aknuds1** [comment]
+1

**Comment by lukeshumard** [comment]
+1. I'd offer some help if needed.

**Comment by ghost** [comment]
+1!

**Comment by JonasVorwerk** [comment]
+2

**Comment by bryancolosky** [comment]
+1

**Comment by solemone** [comment]
+1

**Comment by hudri** [comment]
+1

**Comment by Gaetan-dc** [comment]
+1 very much. Infinite scrolling is a staple feature nowadays.

**Comment by desandro** [comment]
**Metafizzy's next project will be Infinite Scroll v3**. See blog post: [Metafizzy taking over Infinite Scroll](https://metafizzy.co/blog/metafizzy-taking-infinite-scroll/)

> Metafizzy is taking over Infinite Scroll. In addition to assuming maintenance of the project, Metafizzy will release a brand new version of Infinite Scroll in the coming weeks.

The Infinite Scroll repo now lives at [metafizzy/infinite-scroll](https://github.com/metafizzy/infinite-scroll/). Star the repo to help support development

Thank you for adding your input on this idea. The sizable response to this issue was a big reason why I ultimately decided to pursue it.

I'm delighted to be bringing the Scroll back to life. Expect the big launch shortly.
