### ISSUE TITLE
Modular Slideshow framework

### ISSUE THREAD

**Issue by xaddict** [metafizzy/next-project#20]
There are a few robust slideshow frameworks available today (the one I like most is Cycle2) but most of these use a library and have ridiculous extensions which blow up their codebase.

I would like to see a modular, plain javascript slideshow framework:
- multiple slideshows per page
- entity-specific timing, delay, etc via data-attributes for example
- effects like fade, slide, move, sliderover, popin, etc

it would be similar to metafizzy's flickity.

**Comment by desandro** [comment]
Thank you for this proposal. **+1 or add a 👍  reaction** if you'd like to see this project by Metafizzy.

**Comment by desandro** [comment]
Thank you for this suggestion. I have decided not to pursue this idea. [Flickity](http://flickityjs.com) is close to this idea, being a carousel. I appreciate your input and hope you continue to be involved in open source. Metafizzy thanks you! 🌈🐻
