### ISSUE TITLE
The Singularity

### ISSUE THREAD

**Issue by kingkool68** [metafizzy/next-project#7]
Machines are pretty dumb. Please make machines smarter so they can eventually improve themselves recursively. Would be helpful if they couldn't decide to wipe out the entire human race.

**Comment by ghost** [comment]
Is this a joke, or what?

**Comment by larryfox** [comment]
+1

**Comment by dennisgaebel** [comment]
everyone can be wiped out except for the humans

**Comment by desandro** [comment]
I've got this fun story concept: AI will arise not from carefully crafted laboratory but from a spam bot. Life is born in the gutters.

Alas, for another time 🤖
